# -*- coding: utf-8 -*-
"""Copy of Base 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Le1KCSDQoT-TsqVhLqiqYsZFxb-Qcmi-
"""

import os
import numpy as np
import matplotlib.pyplot as plt
#import streamlit as st

from pathlib import Path
from collections import Counter

import tensorflow as tf
from tensorflow import keras
from keras import layers
from keras import ops

import kagglehub
path = kagglehub.dataset_download("kiranbudati/1-million-captcha-images")

print(os.listdir(path))

data_dir = Path(path)

images = sorted(list(map(str, list(data_dir.glob("part1/**/*.png")))))
labels = [img.split(os.path.sep)[-1].split(".png")[0] for img in images]
characters = set(char for label in labels for char in label)

print("Number of images found: ", len(images))
print("Number of labels: ", len(labels))
print("Number of characters: ", len(characters))
print("Chars: ", characters)

batch_size = 32

img_width = 200
img_height = 50

downsample_factor = 4

max_length = max([len(label) for label in labels])

char_to_num = layers.StringLookup(vocabulary=list(characters), mask_token=None)

num_to_char = layers.StringLookup(
    vocabulary=char_to_num.get_vocabulary(), mask_token=None, invert=True
)


def split_data(images, labels, train_size=0.09, shuffle=True):
    size = len(images)
    indices = ops.arange(size)
    if shuffle:
        indices = keras.random.shuffle(indices)
    train_samples = int(size * train_size)
    x_train, y_train = images[indices[:train_samples]], labels[indices[:train_samples]]
    x_valid, y_valid = images[indices[train_samples:]], labels[indices[train_samples:]]
    return x_train, x_valid, y_train, y_valid

x_train, x_valid, y_train, y_valid = split_data(np.array(images), np.array(labels))


def encode_single_sample(img_path, label):
    img = tf.io.read_file(img_path)
    img = tf.io.decode_png(img, channels=1)
    img = tf.image.convert_image_dtype(img, tf.float32)
    img = ops.image.resize(img, [img_height, img_width])
    img = ops.transpose(img, axes=[1, 0, 2])

    label = char_to_num(tf.strings.unicode_split(label, input_encoding="UTF-8"))
    return {"image": img, "label": label}

train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = (
    train_dataset
    .map(encode_single_sample, num_parallel_calls=tf.data.AUTOTUNE)
    .cache()
    .batch(batch_size)
    .prefetch(buffer_size=tf.data.AUTOTUNE)
)

validation_dataset = tf.data.Dataset.from_tensor_slices((x_valid, y_valid))
validation_dataset = (
    validation_dataset.map(
        encode_single_sample, num_parallel_calls=tf.data.experimental.AUTOTUNE
    )
    .batch(batch_size)
    .prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
)
print(len(train_dataset))

_, ax = plt.subplots(4, 4, figsize=(10, 5))
for batch in train_dataset.take(1):
    images = batch["image"]
    labels = batch["label"]
    for i in range(16):
        img = (images[i] * 255).numpy().astype("uint8")
        label = tf.strings.reduce_join(num_to_char(labels[i])).numpy().decode("utf-8")
        ax[i // 4, i % 4].imshow(img[:, :, 0].T, cmap="gray")
        ax[i // 4, i % 4].set_title(label)
        ax[i // 4, i % 4].axis("off")
plt.show()

class CTCLayer(layers.Layer):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.loss_fn = keras.backend.ctc_batch_cost

  def call(self, y_true, y_pred):
    batch_len = tf.cast(tf.shape(y_true)[0], dtype="int64")
    input_length = tf.cast(tf.shape(y_pred)[1], dtype="int64")
    label_length = tf.cast(tf.shape(y_true)[1], dtype="int64")

    input_length = input_length * tf.ones(shape=(batch_len, 1), dtype="int64")
    label_length = label_length * tf.ones(shape=(batch_len, 1), dtype="int64")

    loss = self.loss_fn(y_true, y_pred, input_length, label_length)
    self.add_loss(loss)

    return y_pred

def build_model():
  input_img = layers.Input(
      shape=(img_width, img_height, 1), name= "image", dtype="float32"
  )
  labels = layers.Input(name="label", shape=(None,), dtype = "int64")

  x = layers.Conv2D(
      32,
      (3, 3),
      activation = "relu",
      kernel_initializer="he_normal",
      padding="same",
      name="Conv1"
  )(input_img)
  x = layers.BatchNormalization()(x)
  x = layers.MaxPooling2D((2, 2), name="pool1")(x)

  x = layers.Conv2D(
      64,
      (3, 3),
      activation = "relu",
      kernel_initializer="he_normal",
      padding="same",
      name="Conv2"
  )(x)
  x = layers.BatchNormalization()(x)
  x = layers.MaxPooling2D((2, 2), name="pool2")(x)

  new_shape = ((img_width // downsample_factor), (img_height // downsample_factor) * 64)
  x = layers.Reshape(target_shape=new_shape, name="reshape")(x)
  x = layers.Dense(64, activation="relu", name="dense1")(x)
  x = layers.BatchNormalization()(x)
  x = layers.Dropout(0.2)(x)

  x = layers.Bidirectional(layers.LSTM(128, return_sequences=True, dropout=0.25))(x)
  x = layers.Bidirectional(layers.LSTM(64, return_sequences=True, dropout=0.25))(x)

  num_classes = char_to_num.vocabulary_size() + 1
  x = layers.Dense(num_classes, activation="softmax", name="dense2")(x)

  output = CTCLayer(name="ctc_loss")(labels, x)

  model = keras.models.Model(
      inputs=[input_img, labels], outputs=output, name="ocr_model_v1"
  )

  opt = keras.optimizers.Adam(clipnorm=1.0)

  model.compile(optimizer=opt)
  return model

model = build_model()
model.summary()

epochs = 15
early_stopping_patience = 10

early_stopping = keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=early_stopping_patience, restore_best_weights=True
)

history = model.fit(
    train_dataset,
    validation_data=validation_dataset,
    epochs=epochs,
    callbacks=[early_stopping],
)

def decode_batch_predictions(pred):
    input_len = ops.ones(pred.shape[0]) * pred.shape[1]

    results = keras.backend.ctc_decode(pred, input_length=input_len, greedy=True)[0][0]

    output_text = []
    for res in results:
        res = tf.gather(res, tf.where(tf.math.not_equal(res, -1)))
        output_text.append(tf.strings.reduce_join(num_to_char(res)).numpy().decode("utf-8"))
    return output_text


def levenshtein_distance(s1, s2):
    if len(s1) < len(s2):
        return levenshtein_distance(s2, s1)

    if len(s2) == 0:
        return len(s1)

    previous_row = range(len(s2) + 1)
    for i, c1 in enumerate(s1):
        current_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previous_row[j + 1] + 1
            deletions = current_row[j] + 1
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row
    return previous_row[-1]


total_edit_distance = 0
total_chars = 0
num_samples = 0


prediction_model = keras.models.Model(
    inputs=[model.get_layer(name="image").output], outputs=model.get_layer(name="dense2").output
)

for batch in validation_dataset:
    images = batch["image"]
    labels = batch["label"]

    preds = prediction_model.predict(images)
    pred_texts = decode_batch_predictions(preds)

    for i in range(len(labels)):
        true_label = tf.strings.reduce_join(num_to_char(labels[i])).numpy().decode("utf-8")
        predicted_label = pred_texts[i]

        total_edit_distance += levenshtein_distance(true_label, predicted_label)
        total_chars += len(true_label)
        num_samples += 1

character_error_rate = total_edit_distance / total_chars if total_chars > 0 else 0
accuracy = (1 - character_error_rate) * 100

test_loss = model.evaluate(validation_dataset, verbose=2)

print("\nFinal Test Loss:", test_loss)
print("\nCharacter Error Rate (CER):", character_error_rate)
print("\nFinal Test Accuracy (1 - CER):", round(accuracy, 2), "%")